### PR TITLE
Explicitly specify source URL (fixes #140)

### LINKED ISSUE #140: Don't assume the source is Repology
Thanks to @Synthetica9 we have a new high-quality source of new versions for GitHub packages. So we need to implement a way to know which source the versions were from and report that in the PR text.

### PR DESCRIPTION
**Pull request by Synthetica9**
Changes the format of the input format from `<name> <oldversion> <newversion>` to `<name> <oldversion> <newversion> <url>`. The old format is also still supported, in that case we don't state the URL in the PR message.

### CODE REVIEW

**Comment by ryantm** [comment]
@Synthetica9 Saw your IRC message. This is probably awesome. I've been sick for a week so I haven't gotten to this, but I plan to soon.

**Comment by ryantm** [comment]
Yeah, this looks great, I'll merge it.

**Comment by ryantm** [comment]
I deployed it and your GitHub source too.

**Comment by Synthetica9** [comment]
Judging by the latest batch of PR's, it works :)

**Comment by ryantm** [comment]
Yes! Thank you.

**Pull request merged**
