### PR TITLE
add darwin platform

### PR DESCRIPTION
**Pull request by happysalada**
Adding support for darwin in the flake.
I tested and it compiled without problem.
Let me know if anything.

### CODE REVIEW

**Comment by ryantm** [comment]
I'd be a little surprised if it actually worked because I bet I'm making some assumption about directory structures or something somewhere but okay, we can try it.

**Comment by happysalada** [comment]
I just want to say that I didn't run into any problems so far. Thanks again for merging this!

**Comment by happysalada** [comment]
I did get the following error when trying the `--nixpkgs-review` option
```
nixpkgs-update: timeout: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
I'll try to debug further.

**Comment by ryantm** [comment]
@happysalada The timeout binary was properly patched to a nix store path in Check.hs but not in NixpkgsReview.hs if the timeout binary can be built for darwin, that that will probably fix it.

**Pull request merged**
