### PR TITLE
Emit logfile names with ISO 8601 standard dates

### PR DESCRIPTION
**Pull request by bhipple**
Namely, `YYYY-MM-DD.log`

### CODE REVIEW

**Comment by bhipple** [comment]
This will require some rename logic to make https://r.ryantm.com/log/ consistent, but I think the ISO 8601 standard dates are preferable in the long run.

**Comment by ryantm** [comment]
This is going to change the behavior, so that in the middle of the run it will change log files, right? I think that will make it harder for someone to process statistics about it, but maybe that's okay.

**Comment by bhipple** [comment]
I don't think it'd change in the middle of a run; it'd change in-between runs on the day (e.g., once an update loop fully finishes and it starts a new round).  That's an issue for a single day, though.

**Comment by ryantm** [comment]
Oh yeah, I miss read it.

**Comment by bhipple** [comment]
In order to avoid any disruption, prior to deployment of the new version:

1. Stop the bot process.
2. `cd <log-dir> && python3 /path/to/this/script.py`:

```python
#!/usr/bin/env python3
import os
import glob

for fname in glob.glob('*.log'):
    if '-' in fname:
        continue
    year = fname[0:4]
    month = fname[4]  # all months so far are 1 digit
    day = fname[5:len(fname)-4]
    if len(day) == 1:
        day = f"0{day}"
    tgt = f"{year}-0{month}-{day}.log"
    print(f"Moving {fname}\t->\t{tgt}")
    os.rename(fname, tgt)
```

3. Start the upgraded bot version.

**Pull request merged**
