### PR TITLE
Check: build passthru.tests when present

### PR DESCRIPTION
**Pull request by Ekleog**
This is my first attempt at haskell in a quite long time, and I haven't been able to `nix-build` the file produced by `cabal2nix` even before my changes (maybe due to my being on 19.03?), so it's quite possible that this does not even parse.

Other than that, I've tried to keep things consistent, and hopefully this should work!

### CODE REVIEW

**Comment by Ekleog** [comment]
(Replacing `<nixpkgs>` with `channel:nixpkgs-unstable` allowed me to test locally)

**Comment by Ekleog** [comment]
(all stupid errors fixed locally, travis should pass now)

**Comment by ryantm** [comment]
Thanks!

**Comment by ryantm** [comment]
https://github.com/NixOS/nixpkgs/pull/63216
@Ekleog 
Looks like something is going wrong because it is creating a warning for packages without tests.

**Comment by ryantm** [comment]
```
pushing /nix/store/s7j02mg1fg6nxiwy0yih5i1fscvq3sih-brial-1.2.5
All done.
mktemp -d
/tmp/tmp.VanUS1zMPa
nix-build --option sandbox true --option restrict-eval true --arg config '{ allowBroken = true; allowUnfree = true; allowAliases = false; }' -E '{ config }: (
import ./. { inherit config; }).brial.tests or {}'
error: access to path '/tmp/tmp.VanUS1zMPa' is forbidden in restricted mode
```

**Comment by Ekleog** [comment]
@ryantm I've submitted a tentative fix in https://github.com/ryantm/nixpkgs-update/pull/119 :)

**Pull request merged**
