### PR TITLE
Port to Haskell

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by ryantm** [comment]
This seems like good way to go. You are basically directly porting the shell scripts to Haskell. After we get this working, we can go in and clean up and structure things better!

**Comment by jtojnar** [comment]
Yep, that was what I am aiming for. Still need to port `check-result` and `fix-src-url`, and then double check I did not botch it up. I am not very proud of the logging, maybe we could use `monad-logger` but I am not very familiar with transformers.

**Comment by ryantm** [comment]
I started working on this too: https://github.com/ryantm/nixpkgs-update/tree/green-to-purple

**Comment by jtojnar** [comment]
Okay, I ported all the interdependent scripts, now it is time for checking and refactoring.

It would be also nice to find some good code pretty printer. I tried Stylish Haskell but it keeps too much of the old formatting (also it does alignment which cannot be turned off :nauseated_face:).

**Comment by ryantm** [comment]
Are you okay releasing this work into the public domain?

**Comment by jtojnar** [comment]
Yes, PD is fine with me.

I tried running the command and got the following error

```ShellSession
$ nix run -f channel:nixos-unstable gitAndTools.hub -c env DRY_RUN=1 ~/nix-update/result/bin/nixpkgs-update --update
2018-04-04T12:21:37+02:00
2018-04-04T12:21:37+02:00
Cloning into '/home/jtojnar/.cache/nixpkgs'...
From https://github.com/NixOS/nixpkgs
 * [new branch]              0.5-stable            -> upstream/0.5-stable
 * [new branch]              cpan-update           -> upstream/cpan-update
 * [new branch]              darwin-callpackage    -> upstream/darwin-callpackage
 * [new branch]              darwin-full-purity    -> upstream/darwin-full-purity
 * [new branch]              darwin-sandbox        -> upstream/darwin-sandbox
 * [new branch]              fake-xcode            -> upstream/fake-xcode
 * [new branch]              fetchurl-user-agent   -> upstream/fetchurl-user-agent
 * [new branch]              freebsd-losser        -> upstream/freebsd-losser
 * [new branch]              generators-codeowners -> upstream/generators-codeowners
 * [new branch]              gnu-kfreebsd          -> upstream/gnu-kfreebsd
 * [new branch]              grsec-stdenv          -> upstream/grsec-stdenv
 * [new branch]              haskell-outputs-bin-etc-lib -> upstream/haskell-outputs-bin-etc-lib
 * [new branch]              hydra                 -> upstream/hydra
 * [new branch]              hydraBump             -> upstream/hydraBump
 * [new branch]              kmod-lib-modules      -> upstream/kmod-lib-modules
 * [new branch]              kube-update           -> upstream/kube-update
 * [new branch]              lib+paths             -> upstream/lib+paths
 * [new branch]              logistics             -> upstream/logistics
 * [new branch]              master                -> upstream/master
 * [new branch]              meteor                -> upstream/meteor
 * [new branch]              mkMap                 -> upstream/mkMap
 * [new branch]              nix-upgrade           -> upstream/nix-upgrade
 * [new branch]              nixos/hardened        -> upstream/nixos/hardened
 * [new branch]              nixpart               -> upstream/nixpart
 * [new branch]              no-requireFile        -> upstream/no-requireFile
 * [new branch]              odroid-xu4            -> upstream/odroid-xu4
 * [new branch]              openssh-drop-dsa      -> upstream/openssh-drop-dsa
 * [new branch]              openssl-1.1           -> upstream/openssl-1.1
 * [new branch]              pam-ssh-security      -> upstream/pam-ssh-security
 * [new branch]              purity-test           -> upstream/purity-test
 * [new branch]              python-unstable       -> upstream/python-unstable
 * [new branch]              python-wip            -> upstream/python-wip
 * [new branch]              python3               -> upstream/python3
 * [new branch]              release-13.10         -> upstream/release-13.10
 * [new branch]              release-14.04         -> upstream/release-14.04
 * [new branch]              release-14.12         -> upstream/release-14.12
 * [new branch]              release-15.09         -> upstream/release-15.09
 * [new branch]              release-16.03         -> upstream/release-16.03
 * [new branch]              release-16.09         -> upstream/release-16.09
 * [new branch]              release-17.03         -> upstream/release-17.03
 * [new branch]              release-17.09         -> upstream/release-17.09
 * [new branch]              release-18.03         -> upstream/release-18.03
 * [new branch]              reproducibility       -> upstream/reproducibility
 * [new branch]              security-updates      -> upstream/security-updates
 * [new branch]              staging               -> upstream/staging
 * [new branch]              staging-18.03         -> upstream/staging-18.03
 * [new branch]              staging.patchShebangs -> upstream/staging.patchShebangs
 * [new branch]              syscall-tracing       -> upstream/syscall-tracing
 * [new branch]              unstable-aarch64      -> upstream/unstable-aarch64
 * [new branch]              whois                 -> upstream/whois
 * [new branch]              x86_64-darwin         -> upstream/x86_64-darwin
 * [new branch]              yegortimoshenko-patch-1 -> upstream/yegortimoshenko-patch-1
 * [new tag]                 17.09                 -> 17.09
 * [new tag]                 18.03                 -> 18.03
fatal: Couldn't find remote ref staging
nixpkgs-update: 
Ran commands: 
readfile /home/jtojnar/nix-update/github_token.txt
readBinary /home/jtojnar/nix-update/github_token.txt
mkdir -p /home/jtojnar/.nixpkgs-update
touch /home/jtojnar/.nixpkgs-update/ups.log
appendfile /home/jtojnar/.nixpkgs-update/ups.log
readfile /home/jtojnar/nix-update/packages-to-update.txt
readBinary /home/jtojnar/nix-update/packages-to-update.txt
appendfile /home/jtojnar/.nixpkgs-update/ups.log
date -Iseconds
which date
appendfile /home/jtojnar/.nixpkgs-update/ups.log
date -Iseconds
which date
appendfile /home/jtojnar/.nixpkgs-update/ups.log
hub clone nixpkgs /home/jtojnar/.cache/nixpkgs
which hub
cd /home/jtojnar/.cache/nixpkgs
git remote add upstream https://github.com/NixOS/nixpkgs
which git
git fetch upstream
which git
git fetch origin staging
which git

Exception: error running: git fetch origin staging
exit status: 128
stderr: fatal: Couldn't find remote ref staging
```

Do we need to fetch `origin/staging` in `setupNixpkgs`? It does not seem to be used anywhere.

**Comment by ryantm** [comment]
> Do we need to fetch origin/staging in setupNixpkgs? It does not seem to be used anywhere.

I fixed this recently in the bash version:

https://github.com/ryantm/nixpkgs-update/commit/209ab394495a77a63d8f51f7166f3cd71b9179e4

**Comment by jtojnar** [comment]
This line:

https://github.com/ryantm/nixpkgs-update/pull/36/files#diff-ba31a557c8217e86af98a6ea80c49091R45

**Comment by ryantm** [comment]
Right. I'm pretty sure those fetches aren't necessary, so I deleted them.

**Comment by ryantm** [comment]
You need to add `gist` and `jq` to your command invocation.

**Comment by jtojnar** [comment]
I want to port `jq` invocation to Haskell (aeson) once we check everything is correctly ported.

**Comment by ryantm** [comment]
Okay, it's also using "tree".

**Comment by ryantm** [comment]
I'm getting stuck on 

```
git push --force --verbose  --set-upstream --repo=origin auto-update/xf86-input-libinput                                                                                                       
Pushing to                                                                                                                                                                                     
fatal: No path specified. See 'man git-pull' for valid url syntax
```
(I tried adding the --verbose and --repo=origin to see if that would help, but the error message is the same as the basic thing.)
It's strange because it works fine when exit the program without cleaning up the branch and run the exact command.

**Comment by ryantm** [comment]
I figured it out: the blank text in the case of no --dry-run option was breaking it. This one got all the way through to the end: https://github.com/NixOS/nixpkgs/pull/38465

Some notes about it:
- missing newline in the check list
- this packaged should have failed for having multiple fetchers in the same file

**Comment by jtojnar** [comment]
Could we use repology-api package directly instead of curl-then-jq?

**Comment by ryantm** [comment]
Yes. I should work on making that be a proper package.

**Comment by jtojnar** [comment]
I think the refactored download URL retrieval would just end up as a copy of `repology-api` so we should probably keep it as is until then.

Also, what are your expectations from this pull request? Is this, perhaps with some more clean-ups, good enough? Or should we port all CLI program invocations to a function calls (`git` → `gi-ggit` or `gitlib-libgit2`, `sed` + `grep` → `text`, `nix` → `hnix` or do we need to create custom bindings, `gist` →  `servant-client`…)

**Comment by ryantm** [comment]
This is getting close to good enough to merge! I've been running it in "production" this morning. A major problem I know about is that it doesn't exit correctly from the fixSrcUrl function because "exit 1" basically exits the entire program instead of just being a non-zero exit code for that Sh part. I'm not sure if the Sh monad has a way to exit early from it without calling into a failing bash script.

**Comment by ryantm** [comment]
There's this issue that sometimes it is running two git commands at once:

```
 echo 'nix eval -f /home/ryantm/.cache/nixpkgs --raw pkgs.telepathy-haze.name'                                                                                                                  
nix eval -f /home/ryantm/.cache/nixpkgs --raw pkgs.telepathy-haze.name                                                                                                                         
which nix                                                                                                                                                                                      
echo 'nix eval --raw '(let pkgs = import ./. {}; in (builtins.parseDrvName pkgs.telepathy-haze.name).name)''                                                                                   
nix eval --raw '(let pkgs = import ./. {}; in (builtins.parseDrvName pkgs.telepathy-haze.name).name)'                                                                                          
which nix                                                                                                                                                                                      
echo 'grep -q 'name = "telepathy-haze-0.8.0.1.1"' /home/ryantm/.cache/nixpkgs/pkgs/applications/networking/instant-messengers/telepathy/haze/default.nix'                                      
grep -q 'name = "telepathy-haze-0.8.0.1.1"' /home/ryantm/.cache/nixpkgs/pkgs/applications/networking/instant-messengers/telepathy/haze/default.nix                                             
which grep                                                                                                                                                                                     
echo 'curl https://repology.org/api/v1/metapackage/telepathy-haze'                                                                                                                             
curl https://repology.org/api/v1/metapackage/telepathy-haze                                                                                                                                    
which curl                                                                                                                                                                                     
echo 'jq '.[].downloads | select(values) | .[]''                                                                                                                                               
jq '.[].downloads | select(values) | .[]'                                                                                                                                                      
which jq                                                                                                                                                                                       
echo 'false'                                                                                                                                                                                   
false                                                                                                                                                                                          
which false                                                                                                                                                                                    
echo 'git reset --hard'                                                                                                                                                                        
git reset --hard                                                                                                                                                                               
which git                                                                                                                                                                                      
echo 'git reset --hard'                                                                                                                                                                        
git reset --hard                                                                                                                                                                               
which git                                                                                                                                                                                      
                                                                                                                                                                                               
Exception: error running: git reset --hard                                                                                                                                                     
exit status: 128                                                                                                                                                                               
stderr: fatal: Unable to create '/home/ryantm/.cache/nixpkgs/.git/index.lock': File exists.                                                                                                    
                                                                                                                                                                                               
Another git process seems to be running in this repository, e.g.                                                                                                                               
an editor opened by 'git commit'. Please make sure all processes                                                                                                                               
are terminated then try again. If it still fails, a git process                                                                                                                                
may have crashed in this repository earlier:                                                                                                                                                   
remove the file manually to continue.
```

**Comment by ryantm** [comment]
This git lock problem has happened to me many times so far, but it isn't reproducible for a particular package update.

**Comment by ryantm** [comment]
It also seems to be intermittently getting stuck on the sleep command:

```
Semi-automatic update generated by https://github.com/ryantm/nixpkgs-update tools.                                                                                                             
                                                                                                                                                                                               
This update was made based on information from https://repology.org/metapackage/rtaudio/versions.                                                                                              
                                                                                                                                                                                               
These checks were done:                                                                                                                                                                        
                                                                                                                                                                                               
- built on NixOS                                                                                                                                                                               
- Warning: no binary found that responded to help or version flags. (This warning appears even if the package isn't expected to have binaries.)                                                
- found 5.0.0 with grep in /nix/store/3vbm71ghxfyrmnzygflnqnnp9ahkbb8f-rtaudio-5.0.0                                                                                                           
- directory tree listing: https://gist.github.com/582488bb4b7dcca81883b85ae296a0bf                                                                                                             
                                                                                                                                                                                               
                                                                                                                                                                                               
[auto-update/rtaudio 45fc07d2ffd] rtaudio: 4.1.2 -> 5.0.0                                                                                                                                      
 1 file changed, 2 insertions(+), 2 deletions(-)                                                                                                                                               
git push --force --set-upstream origin auto-update/rtaudio                                                                                                                                     
To github.com:r-ryantm/nixpkgs.git                                                                                                                                                             
 * [new branch]              auto-update/rtaudio -> auto-update/rtaudio                                                                                                                        
Branch auto-update/rtaudio set up to track remote branch auto-update/rtaudio from origin.                                                                                                      
nix eval -f . '(let pkgs = import ./. {}; in pkgs.rtaudio.meta.broken or false)'                                                                                                               
false                                                                                                                                                                                          
Sleeping 790.538686875s seconds. 
```

**Comment by ryantm** [comment]
I'm going to try to run it with strace on the entire time to see if I can find out anything interesting.

I hope you don't mind if I change the indentation of everything to be 2 spaces.

**Comment by jtojnar** [comment]
IIRC I sometimes get this error in [python script](https://github.com/NixOS/nixpkgs/pull/33086) calling `git` even though [`subprocess.call`](https://docs.python.org/3.6/library/subprocess.html#subprocess.call) is supposed to wait for command to complete. Was not able to figure it out. `GIT_TRACE` env var might be useful. Or `GIT_OPTIONAL_LOCKS`.

Alternately, we could do something like

```haskell
git :: [Text] -> Sh Text
git = (>>= \out -> sleep 1 >> return out) . run "git"
```
not sure how to make it variadic.

**Comment by jtojnar** [comment]
I prefer four spaces since it is easier to make out the structure, compare

image

and

image

Ideally, we would use tabs and I could set them to four and you to two but since the tab indentation is frowned upon, I suggest we force the style used by hindent and I will use smudge & clean filters to convert it to something I am comfortable with.

**Comment by ryantm** [comment]
Here is a proper strace of the getting stuck while sleeping issue: https://gist.github.com/5834fd8e5750e39a14265a4c6e968731

**Comment by ryantm** [comment]
I think my issue with git locks was actually me accidentally running nixpkgs-update twice. Probably related to this sleeping bug because when I Ctrl-C out of the sleeping bug, it keeps running in the background.

**Comment by ryantm** [comment]
Yay, it's on master; thanks @jtojnar for your help! I added you to the project's collaborators list.

**Pull request merged**
