### PR TITLE
indicate that contributors also waive their copyrights

### PR DESCRIPTION
**Pull request by ryantm**
It is my intention that this work be released into the public domain by waiving copyrights.  I want to minimize the chances of anyone forcing anyone to do anything related to this work.  

I have waived all my copyrights in the license file. Please indicate you waive your copyrights relating to this project by commenting below:

"To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update."

Once all the contributors have agreed, or their work has been removed from the repository, I will merge this pull request.

~~@jtojnar~~
@matthewbauer 
~~@tomberek~~
~~@worldofpeace~~
@bhipple 
~~@Synthetica9~~
~~@yegortimoshenko~~
@Mic92

### CODE REVIEW

**Comment by worldofpeace** [comment]
To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

Warmth :fire: .

**Comment by tomberek** [comment]
To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

**Comment by jtojnar** [comment]
I think I have already done this but since the waiver is idempotent, let's have it in a single place: To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

**Comment by armijnhemel** [comment]
I would recommend to hold off on this until after you have gotten some advise from a copyright lawyer, as what you suggest might actually not be possible in certain jurisdictions.

**Comment by ryantm** [comment]
@armijnhemel the possibility of inability to waive copyright does not seem like reason to hold off.

**Comment by armijnhemel** [comment]
Actually it is a big red flag, because then you simply don't know and people will have not given you a license to use it, but you would have to assume "proprietary". Please don't do this.

**Comment by ryantm** [comment]
@armijnhemel I bet all licenses are not valid in some jurisdiction. If you know some jurisdictions that do not allow a copyright waiver under law, then it would be great to see the list so we can exclude those people's works from the project.

**Comment by ryantm** [comment]
For reference, my jurisdiction (the 9th circuit court of the United States) has specific case law about copyright waivers, which djb references here http://cr.yp.to/publicdomain.html

**Comment by armijnhemel** [comment]
Please talk to a qualified lawyer before you are doing this. US law doesn't apply anywhere but the US. In jurisdictions such as Germany and France, and possibly others as well, it takes a lot more to transfer copyrights, or it is impossible. It would make this project no longer open source.

**Comment by Synthetica9** [comment]
To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

For the whole line I committed :P

**Comment by yegortimoshenko** [comment]
> I would recommend to hold off on this until after you have gotten some advise from a copyright lawyer, as what you suggest might actually not be possible in certain jurisdictions.

It's highly controversial, even among copyright lawyers, whether or not copyright can be waived in jurisdictions like Germany. There are both sides to the story, and there are ways to waive copyright that do account for those jurisdictions, like CC0-1.0 which specifically has text covering those jurisdictions (although maybe not as concise as a trivial public domain waiver).

As an example, [nixos-hardware](https://github.com/NixOS/nixos-hardware) is under CC0-1.0, to enable users to copy stuff around without having to comply to licenses. Also, most of my repos and upstream contributions are under CC0-1.0.

That said, SQLite and most software written by DJB use trivial public domain waivers. There has not been a legal precedent, ever, that would find these waivers to be insufficient.

Either way: to the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

**Comment by ryantm** [comment]
@armijnhemel Can you recommend a qualified lawyer?

Currently, since I didn't have a good license or contributing policy in place, the project is clearly proprietary. I don't think doing this waiver will make it less proprietary, but you're right, it might not make it fully open either.

**Comment by armijnhemel** [comment]
Just verified with a lawyer in Germany: highly questionable this would work in Germany.

**Comment by armijnhemel** [comment]
> @armijnhemel Can you recommend a qualified lawyer?
> 
> Currently, since I didn't have a good license or contributing policy in place, the project is clearly proprietary. I don't think doing this waiver will make it less proprietary, but you're right, it might not make it fully open either.

We probably need to talk offline about this.

**Comment by jtojnar** [comment]
https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain already covers this nicely. It is true that, for example, in Czech Republic, where I live, it is not possible to waive copyright but it is possible to license the work to everyone under conditions that allow unrestricted use. I am not a lawyer but I would say the formulation above sufficiently carries the intended meaning. 

If we want to be more explicit, we can use [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by silverhook** [comment]
Yeah, you simply can’t waive your copyright in (many parts of) Europe. If memory serves me right, it’s only actually possible in England and Wales. At the very least, you are stuck with moral rights.

The closest you can get to a full copyright waiver/actual public domain is, as @yegortimoshenko and @jtojnar already mentioned, use something like CC0-1.0, which was specifically written to tackle this issue in an international setting.

(IMNYL TINLA bla bla bla)

**Comment by Mic92** [comment]
To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

**Comment by ryantm** [comment]
I read CC0-1.0 and it looks fine to me. @armijnhemel Thanks for your help. I do not know how to contact you outside of GitHub. Could you email me ryan at ryantm.com ? I'd like to ask you a question about how best to transition to CC0-1.0.

**Comment by armijnhemel** [comment]
> I read CC0-1.0 and it looks fine to me. @armijnhemel Thanks for your help. I do not know how to contact you outside of GitHub. Could you email me ryan at ryantm.com ? I'd like to ask you a question about how best to transition to CC0-1.0.

I tried pinging you on IRC :-)

**Comment by bhipple** [comment]
To the extent possible under law, I have waived all copyright and related or neighboring rights to nixpkgs-update.

**Pull request closed without merging**
