### PR TITLE
Add nix build command to Update.hs

### PR DESCRIPTION
**Pull request by mig4ng**
Add new command to the PR which allows to build the package with the new nix commands. E.g.:
```
nix build github:r-ryantm/nixpkgs/5026173792d483cd22517456c2b218655717e6f9#kubevpn
```

Feel free to edit the place or text as you wish. Thanks for making this tool, it helps me keep the package I maintain up to date.

### CODE REVIEW

**Review by rhendric — APPROVED** [review]

**Comment by mig4ng** [comment]
@rhendric tests were broken because the PR test data needed the extra command. I think I fixed it.

**Comment by mig4ng** [comment]
I am not sure what is still breaking. I tried to run `nix build --accept-flake-config` locally but it is throwing a darwin error.

**Comment by rhendric** [comment]
Looking at the git diff, you may have changed some line endings in the golden test files? I wonder if that's the problem.

**Comment by mig4ng** [comment]
Changed to my linux machine to be able to run the test command locally. It is fixed now. It was indeed the newlines :sweat_smile:

**Review by rhendric — APPROVED** [review]

**Comment by mig4ng** [comment]
Hi @ryantm , how does the deployment of this bot works? I don't think this is yet running in it 😄

**Pull request merged**
