### PR TITLE
increase python max package rebuilds from 10 to 25

### PR DESCRIPTION
**Pull request by ryantm**
@jonringer requested this change but he wanted me to cc @fridh to make sure he's okay with it.

### CODE REVIEW

**Comment by FRidh** [comment]
Sure

**Comment by zowoq** [comment]
Would it make sense to increase this to 500 to match the master branch cutoff (>500 goes to staging and skips nixpkgs-review)?

cc @mweinelt

**Comment by mweinelt** [comment]
I guess, but even 100 or 250 would be a cool upgrade. Really depends on how busy the builder behind this setup is.

**Comment by zowoq** [comment]
Apart from a bit of a slowdown while it is catching up with the newly allowed updates the builder should be fine.

Something that may be an issue is nixpkgs-review step, currently it has a 45 minute timeout. I've opened a PR to increase it to 120 minutes, do you think that would be enough?

**Comment by mweinelt** [comment]
Yeah, that would certainly do it, unless you run into any of the weird packages like tensorflow, torch or similar.

**Comment by zowoq** [comment]
Increasing the timeout and the python rebuilds are in https://github.com/ryantm/nixpkgs-update/pull/399.

**Pull request merged**
